### ISSUE TITLE
Разные цвета букв заставки

### ISSUE THREAD

**Issue by 555Shaman555** [freehackquest/frontend#3]
На заставке 3 буквы: F, H, Q. Q - синего цвета, остальные черного

**Comment by sea-kg** [comment]
Где ?

Вот оригиналы:
https://github.com/freehackquest/frontend/blob/master/src/logo/fhq_2017_white.svg
https://github.com/freehackquest/frontend/blob/master/src/logo/fhq_2017_white.png

В упор не вижу где она там синего цвета )))

**Comment by 555Shaman555** [comment]
Может из-за оформления и анимации так кажется. Просто я еще у дригх людей поблизости спрашивал

**Comment by sea-kg** [comment]
Я вспомнил это фича )))
